global_frame: robot_pose_ekf/odom_combined
rolling_window: true

plugins:
  - {name: obstacles_laser,          type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
